Android Properties

#Appium Settings
appium.hub=http://127.0.0.1:4723/wd/hub
appium.autoLaunch=true
appium.noReset=true
appium.platformName=Android
webdriver.driver=appium
appium.automationName=UiAutomator2
appium.udid=ZD222HHHQV
appium.deviceName=ZD222HHHQV
appium.platformVersion=15
appium.appWaitActivity=com.act.mobile.apps.MainActivity
appium.appWaitPackage=com.act.mobile.apps
appium.app=/absolute/path/to/wherever/you/built/app_name.apk


#Serenity
serenity.extension.packages=
serenity.pagesource.outputoverride=off
serenity.logging=VERBOSE
serenity.console.colors=TRUE

#--WebDriver timeout
serenity.timeout=10000
webdriver.timeouts.implicitlywait=10000
webdriver.wait.for.timeout=10000
webdriver.autodownload=false

#Splunk OFF for local run
splunk.logging=false